package com.ardrawing.sketch.anime.drawing.ui.home

import com.ardrawing.sketch.anime.drawing.R


data class DetailModel(var img: Int)
data class FavoriteModel(var img: Int)

class HomeModel(
    var id: Int,
    var img: Int,
    var title: Int,
    var list: List<DetailModel> = mutableListOf()
)

val listHome = listOf(
    HomeModel(
        1,
        R.drawable.img_cartoon_01,
        R.string.cartoons,
        listOf(
            DetailModel(R.drawable.img_cartoon_01),
            DetailModel(R.drawable.img_cartoon_02),
            DetailModel(R.drawable.img_cartoon_03),
            DetailModel(R.drawable.img_cartoon_04),
            DetailModel(R.drawable.img_cartoon_05),
            DetailModel(R.drawable.img_cartoon_06),
            DetailModel(R.drawable.img_cartoon_07),
            DetailModel(R.drawable.img_cartoon_08),
            DetailModel(R.drawable.img_cartoon_09),
            DetailModel(R.drawable.img_cartoon_10),
            DetailModel(R.drawable.img_cartoon_11),
            DetailModel(R.drawable.img_cartoon_12),
            DetailModel(R.drawable.img_cartoon_13),
            DetailModel(R.drawable.img_cartoon_14),
            DetailModel(R.drawable.img_cartoon_15),
        )
    ),
    HomeModel(
        2,
        R.drawable.img_animals_1,
        R.string.animals,
        listOf(
            DetailModel(R.drawable.img_animals_1),
            DetailModel(R.drawable.img_animals_10),
            DetailModel(R.drawable.img_animals_3),
            DetailModel(R.drawable.img_animals_4),
            DetailModel(R.drawable.img_animals_5),
            DetailModel(R.drawable.img_animals_6),
            DetailModel(R.drawable.img_animals_7),
            DetailModel(R.drawable.img_animals_8),
            DetailModel(R.drawable.img_animals_9),
            DetailModel(R.drawable.img_animals_10),
            DetailModel(R.drawable.img_animals_11),
            DetailModel(R.drawable.img_animals_12),
            DetailModel(R.drawable.img_animals_13),
            DetailModel(R.drawable.img_animals_14),
            DetailModel(R.drawable.img_animals_15),
        )
    ),
    HomeModel(
        3,
        R.drawable.img_people_01,
        R.string.people,
        listOf(
            DetailModel(R.drawable.img_people_01),
            DetailModel(R.drawable.img_people_02),
            DetailModel(R.drawable.img_people_03),
            DetailModel(R.drawable.img_people_04),
            DetailModel(R.drawable.img_people_05),
            DetailModel(R.drawable.img_people_06),
            DetailModel(R.drawable.img_people_07),
            DetailModel(R.drawable.img_people_08),
            DetailModel(R.drawable.img_people_09),
            DetailModel(R.drawable.img_people_10),
            DetailModel(R.drawable.img_people_11),
            DetailModel(R.drawable.img_people_12),
            DetailModel(R.drawable.img_people_13),
            DetailModel(R.drawable.img_people_14),
            DetailModel(R.drawable.img_people_15),
        )
    ),
    HomeModel(
        4,
        R.drawable.img_anime_01,
        R.string.anime,
        listOf(
            DetailModel(R.drawable.img_anime_01),
            DetailModel(R.drawable.img_anime_02),
            DetailModel(R.drawable.img_anime_03),
            DetailModel(R.drawable.img_anime_04),
            DetailModel(R.drawable.img_anime_05),
            DetailModel(R.drawable.img_anime_06),
            DetailModel(R.drawable.img_anime_07),
            DetailModel(R.drawable.img_anime_08),
            DetailModel(R.drawable.img_anime_09),
            DetailModel(R.drawable.img_anime_10),
            DetailModel(R.drawable.img_anime_11),
            DetailModel(R.drawable.img_anime_12),
            DetailModel(R.drawable.img_anime_13),
            DetailModel(R.drawable.img_anime_14),
            DetailModel(R.drawable.img_anime_15),
        )
    ),
    HomeModel(
        5,
        R.drawable.img_car_01,
        R.string.cars,
        listOf(
            DetailModel(R.drawable.img_car_01),
            DetailModel(R.drawable.img_car_02),
            DetailModel(R.drawable.img_car_03),
            DetailModel(R.drawable.img_car_04),
            DetailModel(R.drawable.img_car_05),
            DetailModel(R.drawable.img_car_06),
            DetailModel(R.drawable.img_car_07),
            DetailModel(R.drawable.img_car_08),
            DetailModel(R.drawable.img_car_09),
            DetailModel(R.drawable.img_car_10),
            DetailModel(R.drawable.img_car_11),
            DetailModel(R.drawable.img_car_12),
            DetailModel(R.drawable.img_car_13),
            DetailModel(R.drawable.img_car_14),
            DetailModel(R.drawable.img_car_15),
        )
    ),
    HomeModel(
        6,
        R.drawable.img_for_kid_01,
        R.string.for_kids,
        listOf(
            DetailModel(R.drawable.img_for_kid_01),
            DetailModel(R.drawable.img_for_kid_02),
            DetailModel(R.drawable.img_for_kid_03),
            DetailModel(R.drawable.img_for_kid_04),
            DetailModel(R.drawable.img_for_kid_05),
            DetailModel(R.drawable.img_for_kid_06),
            DetailModel(R.drawable.img_for_kid_07),
            DetailModel(R.drawable.img_for_kid_08),
            DetailModel(R.drawable.img_for_kid_09),
            DetailModel(R.drawable.img_for_kid_10),
            DetailModel(R.drawable.img_for_kid_11),
            DetailModel(R.drawable.img_for_kid_12),
            DetailModel(R.drawable.img_for_kid_13),
            DetailModel(R.drawable.img_for_kid_14),
            DetailModel(R.drawable.img_for_kid_15),
        )
    ),
    HomeModel(
        7,
        R.drawable.img_flowers_01,
        R.string.flowers,
        listOf(
            DetailModel(R.drawable.img_flowers_01),
            DetailModel(R.drawable.img_flowers_02),
            DetailModel(R.drawable.img_flowers_03),
            DetailModel(R.drawable.img_flowers_04),
            DetailModel(R.drawable.img_flowers_05),
            DetailModel(R.drawable.img_flowers_06),
            DetailModel(R.drawable.img_flowers_07),
            DetailModel(R.drawable.img_flowers_08),
            DetailModel(R.drawable.img_flowers_09),
            DetailModel(R.drawable.img_flowers_10),
            DetailModel(R.drawable.img_flowers_11),
            DetailModel(R.drawable.img_flowers_12),
            DetailModel(R.drawable.img_flowers_13),
            DetailModel(R.drawable.img_flowers_14),
            DetailModel(R.drawable.img_flowers_15),
        )
    ),
    HomeModel(
        8,
        R.drawable.img_chibi_01,
        R.string.chibis,
        listOf(
            DetailModel(R.drawable.img_chibi_01),
            DetailModel(R.drawable.img_chibi_02),
            DetailModel(R.drawable.img_chibi_03),
            DetailModel(R.drawable.img_chibi_04),
            DetailModel(R.drawable.img_chibi_05),
            DetailModel(R.drawable.img_chibi_06),
            DetailModel(R.drawable.img_chibi_07),
            DetailModel(R.drawable.img_chibi_08),
            DetailModel(R.drawable.img_chibi_09),
            DetailModel(R.drawable.img_chibi_10),
            DetailModel(R.drawable.img_chibi_11),
            DetailModel(R.drawable.img_chibi_12),
            DetailModel(R.drawable.img_chibi_13),
            DetailModel(R.drawable.img_chibi_14),
            DetailModel(R.drawable.img_chibi_15),
        )
    ),
    )
